// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	transaction "project/e-commerce/features/transaction"

	mock "github.com/stretchr/testify/mock"
)

// TransactionData is an autogenerated mock type for the DataInterface type
type TransactionData struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: token, status
func (_m *TransactionData) CancelOrder(token int, status string) (int, error) {
	ret := _m.Called(token, status)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, string) int); ok {
		r0 = rf(token, status)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(token, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertData provides a mock function with given fields: token, data, dataPay
func (_m *TransactionData) InsertData(token int, data transaction.AddressCore, dataPay transaction.PaymentCore) (int, error) {
	ret := _m.Called(token, data, dataPay)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, transaction.AddressCore, transaction.PaymentCore) int); ok {
		r0 = rf(token, data, dataPay)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, transaction.AddressCore, transaction.PaymentCore) error); ok {
		r1 = rf(token, data, dataPay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectOrder provides a mock function with given fields: token
func (_m *TransactionData) SelectOrder(token int) ([]transaction.HistoryOrder, error) {
	ret := _m.Called(token)

	var r0 []transaction.HistoryOrder
	if rf, ok := ret.Get(0).(func(int) []transaction.HistoryOrder); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.HistoryOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: token, status
func (_m *TransactionData) UpdateStatus(token int, status string) (int, error) {
	ret := _m.Called(token, status)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, string) int); ok {
		r0 = rf(token, status)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(token, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionData interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionData creates a new instance of TransactionData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionData(t mockConstructorTestingTNewTransactionData) *TransactionData {
	mock := &TransactionData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
